version: "3.7"

services:

  draco:
    build: .
    image: calini/draco:dev
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"

  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: whatever